<Gerenciador>:
    Menu:
        name: 'menu'
    Tarefas:
        name: 'tarefas'
    Calculo:
        name: 'calculo'
    IMC:
        name: 'imc'
    CALCULADORA:
        name:'calculadora'
    TMB:
        name: 'tmb'
    TAXACALORICA:
        name: 'taxacalorica'
    historico_imc:
        name: 'historico'
    historico_tmb:
        name:'historico_tmb'
    historico_atv:
        name:'historico_atv'
    perfil:
        name:'perfil'
    resultados:
        name:'resultados'

<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:root.width*0.25,root.height*0.1
        spacing:'30dp'
        canvas:
            Color:
                rgba:1,0.515,0,1
            Rectangle:
                size:self.size
                pos:self.pos
             #   source:'image/moldura.png'
        Image:
            source:'image/LOGO.jpg'
            size_hint_y:3
            canvas:
                Color:
                    rgb: (1, 1, 1)
                Rectangle:
                    texture: self.texture
                    size: self.width + 30, self.height + 150
                    pos: self.x, self.y  - 45
            #allow_stretch:True
        Botao:
            text:'Calculos'
            
            on_release:app.root.current = 'calculo'
            cor:0.1,0.1,0.1,1
        Botao:
            text:'Meu Perfil'
            
            on_release:app.root.current = 'perfil'
            cor:0.1,0.1,0.1,1
        Botao:
            text:'Sair'
            cor:0.1,0.1,0.1,1
            on_release:root.confirmacao()




<perfil>:
    BoxLayout:

        orientation:'vertical'
        canvas:
            Color:
                rgba:1,0.515,0,1
            Rectangle:
                size:self.size
                pos:self.pos
        ActionBar:
            ActionView:
                ActionPrevious:
                    icon: 'image/bat.png'
                    title:'Dados de seu Perfil'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    #icon: 'sair.jpeg'
                    text:'Consultar o seu Status de IMC e TMB aqui!'
                    on_release:app.root.current='resultados'
                ActionButton:
                    icon: 'image/bat.png'
                    text:'Menu'
                    on_release:app.root.current ='menu'
                ActionButton:
                    #icon: 'sair.jpeg'
                    text:'Sair'
                    on_release:app.stop()

        BoxLayout:
            orientation:'vertical'
            padding: 50
            spacing:5
            #padding:root.width*0.25,root.height*0.1
            BoxLayout:
                size_hint_y:None
                orientation:'vertical'
                height:35
                Label:
                    text:'Perfil do Usuario'
                    font_size:35
                    color:0,0,0,1

            GridLayout:
                id: box
                rows: 5
                cols: 1
                #padding: 10
                spacing: 15


                BoxLayout:
                    Label:
                        font_size: 18
                        text:'Digite o seu peso : '
                        color:0,0,0,1
                    TextInput:
                        id:peso_texto
                        font_size: 35
                        height: '50dp'
                        width:'10dp'
                        multiline: False



                BoxLayout:
                    Label:
                        font_size: 18
                        text:'Digite a sua idade : '
                        color:0,0,0,1
                    TextInput:
                        id:idade_texto
                        font_size: 35
                        height: '50dp'
                        width:'10dp'
                        multiline: False

                BoxLayout:
                    #padding:1
                    Label:
                        font_size: 18
                        text:'Selecione o Sexo : '
                        color:0,0,0,1
                        height: '15dp'

                    BoxLayout:
                        orientation:'vertical'

                        BoxLayout:
                            orientation:'horizontal'
                            CheckBox:
                                group: 'check'
                                id: chk_f
                                color:0,0,0,1
                            Label:
                                text:'Feminino'
                                color:0,0,0,1

                        BoxLayout:
                            orientation:'horizontal'
                            CheckBox:
                                group: 'check'
                                color:0,0,0,1
                                id: chk_m
                            Label:
                                color:0,0,0,1
                                text:'Masculino'

                BoxLayout:
                    Label:
                        font_size: 18
                        text:'Digite a sua altura : '
                        color:0,0,0,1
                    TextInput:
                        id:altura_texto
                        font_size: 35
                        height: '50dp'
                        width:'10dp'
                        multiline: False

                BoxLayout:
                    id:bx_btn
                    padding:5
                    Botao_confirma:
                        id:ok_btn
                        font_size: 18
                        text:'Gravar'
                        color:0,0,0,1
                        on_release:root.atualizar()
                    Botao_cancelar:
                        id: limpar
                        font_size: 18
                        text:'Cancelar'
                        color:0,0,0,1
                        on_release:app.root.current ='menu'


<resultados>:
    BoxLayout:

        orientation:'vertical'
        canvas:
            Color:
                rgba:1,0.515,0,1
            Rectangle:
                size:self.size
                pos:self.pos
        ActionBar:
            ActionView:
                ActionPrevious:
                    icon: 'image/bat.png'
                    title:'Dados de seu Perfil'
                    on_release:app.root.current = 'perfil'
                ActionButton:
                    icon: 'image/bat.png'
                    text:'Menu'
                    on_release:app.root.current ='menu'
                ActionButton:
                    #icon: 'sair.jpeg'
                    text:'Sair'
                    on_release:app.stop()

        BoxLayout:
            orientation:'vertical'
            padding: 50
            spacing:5
            #padding:root.width*0.25,root.height*0.1
            BoxLayout:
                size_hint_y:None
                orientation:'vertical'
                height:35
                Label:
                    text:'Status do Usuario'
                    font_size:35
                    color:0,0,0,1
            GridLayout:
                id: box
                rows: 2
                cols: 2
                #padding: 10
                spacing: 1

                Label:
                    text:'Indice de Massa corporal:'
                    font_size:25
                    color:0,0,0,1

                Label:
                    id:r_imc
                    text:''
                    font_size:25
                    color:0,0,0,1

                Label:
                    text:'Taxa Metabolica Basal:'
                    font_size:25
                    color:0,0,0,1

                Label:
                    id:r_tbm
                    text:''
                    font_size:25
                    color:0,0,0,1


<Botao_cancelar@ButtonBehavior+Label>:
    canvas.before:
        Color:
            rgba:1,0,0.3,1
        Ellipse:
            pos: self.pos
            size: self.height,self.height
        Ellipse:
            pos: self.x+self.width-self.height,self.y
            size: self.height,self.height
        Rectangle:
            pos:self.x+self.height/2.0,self.y
            size:self.width-self.height,self.height

<Botao_confirma@ButtonBehavior+Label>:
    canvas.before:
        Color:
            rgba:0.2,1,0.3,1
        Ellipse:
            pos: self.pos
            size: self.height,self.height
        Ellipse:
            pos: self.x+self.width-self.height,self.y
            size: self.height,self.height
        Rectangle:
            pos:self.x+self.height/2.0,self.y
            size:self.width-self.height,self.height

<Botao_redondo@ButtonBehavior+Label>:
    canvas.before:
        Color:
            rgba:0.3,0.3,0.3,1
        Ellipse:
            pos: self.pos
            size: self.height,self.height
        Ellipse:
            pos: self.x+self.width-self.height,self.y
            size: self.height,self.height
        Rectangle:
            pos:self.x+self.height/2.0,self.y
            size:self.width-self.height,self.height

<Botao_image@ButtonBehavior+Image+Label>:
    canvas.before:
        Color:
            rgba:0,0,0,1
        Ellipse:
            pos: self.pos
            size: self.height,self.height
        Ellipse:
            pos: self.x+self.width-self.height,self.y
            size: self.height,self.height
        Rectangle:
            pos:self.x+self.height/2.0,self.y
            size:self.width-self.height,self.height



<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    icon: 'image/bat.png'
                    title:'Tarefas'
                    on_release:app.root.current = 'calculo'
                ActionButton:
                    icon: 'image/bat.png'
                    text:'Menu'
                    on_release:app.root.current ='menu'
                ActionButton:
                    #icon: 'sair.jpeg'
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:'40sp'
            TextInput:
                id:texto
            Button:
                text:'+'
                size_hint_x:None
                width:'40sp'
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:'100sp'
    Label:
        id:label
        font_size:'20sp'
    Button:
        text:'X'
        size_hint_x:None
        width:'40sp'
        on_release:app.root.get_screen('tarefas').removeWidget(root)




<Calculo>:
    
    BoxLayout:
        
        orientation:'vertical'
        canvas:
            Color:
                rgba:1,0.515,0,1
            Rectangle:
                size:self.size
                pos:self.pos
       
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Calculadoras TopHealth'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        BoxLayout:
            #height:'550dp'
            #padding:root.width*0.25,root.height*0.1
            orientation:'vertical'
            #padding:'50dp'
            #spacing:'20dp'
            #label:
            GridLayout:
                id: box
                rows: 1
                cols: 3
                padding: 15
                spacing: 35
                ImageButton:  #aqui definimos o widget que incorpora ambos comportamentos
                    source: 'image/txex.png'
                    #text:'Taxa Calorica'
                    on_release:app.root.current = 'taxacalorica'
                    #height:self.minimum_height
                ImageButton:
                    source: 'image/imc.png'
                    #text:'IMC'
                    on_release:app.root.current = 'imc'
                    #height:self.minimum_height

                ImageButton:
                    source: 'image/ibm.png'
                    on_release:app.root.current = 'tmb'
                    #height:self.minimum_height

           # floatButton:
            #    text: '%s'%(icon{'zmdi-github',32})


        BoxLayout:
            GridLayout:
                id: box
                rows: 1
                cols: 2
                padding: 15
                spacing: 35

                ImageButton:
                    source: 'image/calculadora.png'
                    on_release:app.root.current = 'calculadora'
                    #height:self.minimum_height
                ImageButton:
                    source: 'image/tarefas.png'
                    on_release:app.root.current = 'tarefas'
                    #height:self.minimum_height


<CustButton@ButtonBehavior+Label>:
    #cor:0.1,0.1,0.1,1
    font_size: 32 
    canvas.before:
        Color:
            rgba:0.1,0.1,0.1,1
        Rectangle:
            size:self.size
            pos:self.pos

<IMC>:
    BoxLayout:
        
        orientation:'vertical'
        canvas:
            Color:
                rgba:1,0.515,0,1
            Rectangle:
                size:self.size
                pos:self.pos
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'IMC'
                    on_release:app.root.current = 'calculo'
                ActionButton:
                    text:'Consultar Historico'
                    on_release:app.root.current = 'historico'
                ActionButton:
                    text:'Inicio'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    #icon: 'image/sair.png'
                    text:'Sair'
                    on_release:app.stop()
        
        BoxLayout:
            
            height:'550dp'
            
            orientation:'vertical'
            #padding:'50sp'
            padding:root.width*0.25,root.height*0.1
            #spacing:'50sp'
            #BoxLayout:
             #   padding:50
              #  Image:
               #     source:'image/imc.jpeg'
              #      #size_hint_y:1
            GridLayout:
                id: box
                rows: 4
                cols: 2
                padding: 0
                spacing: 5

               
                Label:
                    font_size: 18
                    text:'Digite o seu peso : '
                    color:0,0,0,1
                    
                TextInput:
                    id:peso_texto
                    font_size: 55
                  #  unicode: True
                  #  height: '5sp'
                  #  width: '5sp'

                Label:
                    font_size: 18
                    text:'Digite a sua altura : '
                    color:0,0,0,1
                TextInput:
                    id:altura_texto
                    font_size: 55
                    multiline: False

                Botao_confirma:
                    id: ok
                    font_size: 18
                    text:'OK'
                    color:0,0,0,1
                    on_release:root.calcular()
                Botao_cancelar:
                    id: limpar
                    font_size: 18
                    text:'Limpar'
                    color:0,0,0,1
                    on_release:root.limpar()
                
                Label:
                    id:valor
                    font_size:18
                    text:'Seu IMC e de'
                    color:0,0,0,1
                Label:
                    id:nt_valor
                    font_size:18
                    color:0,0,0,1

<historico_tmb>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    #icon: 'image/bat.png'
                    title:'Historico do TMB'
                    on_release:app.root.current = 'tmb'
                ActionButton:
                    icon: 'image/bat.png'
                    text:'Menu'
                    on_release:app.root.current ='menu'
                ActionButton:
                    #icon: 'sair.jpeg'
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height

<historico_imc>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    icon: 'image/bat.png'
                    title:'Historico'
                    on_release:app.root.current = 'imc'
                ActionButton:
                    icon: 'image/bat.png'
                    text:'Menu'
                    on_release:app.root.current ='menu'
                ActionButton:
                    #icon: 'sair.jpeg'
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        

<Historicos>:
    size_hint_y:None
    height:'100sp'
    Label:
        id:label
        font_size:'20sp'
    Button:
        text:'X'
        size_hint_x:None
        width:'40sp'
        on_release:app.root.get_screen('historico').removeWidget(root)


<Historicos_tmb>:
    size_hint_y:None
    height:'100sp'
    Label:
        id:label
        font_size:'20sp'
    Button:
        text:'X'
        size_hint_x:None
        width:'40sp'
        on_release:app.root.get_screen('historico_tmb').removeWidget(root)


<Historicos_taxa>:
    size_hint_y:None
    height:'100sp'
    Label:
        id:label
        font_size:'20sp'
    Button:
        text:'X'
        size_hint_x:None
        width:'40sp'
        on_release:app.root.get_screen('historico_atv').removeWidget(root)

<TMB>:

    BoxLayout:
        
        orientation:'vertical'
        canvas:
            Color:
                rgba:1,0.515,0,1
            Rectangle:
                size:self.size
                pos:self.pos
        ActionBar:
            
            ActionView:
                
                ActionPrevious:
                    title:'Taxa Metabolica Basal'
                    on_release:app.root.current = 'calculo'
                ActionButton:
                    text:'Consultar Historico'
                    on_release:app.root.current = 'historico_tmb'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
          

        BoxLayout:
            #spacing: 10
            padding: 50
            GridLayout:
                id: box
                rows: 6
                cols: 2
                #padding: 10
                spacing: 10

               #1
                Label:
                    font_size: 18
                    color:0,0,0,1
                    text:'Altura: '
                
                Label:
                    font_size: 18
                    text:'Sexo :'
                    color:0,0,0,1
                 #2  
                TextInput:
                    id:altura
                    color:0,0,0,1
                    font_size: 26
                  # unicode: True
                  #  height: '5sp'
                  #  width: '5sp'

               
                BoxLayout:  
                    CheckBox:
                        group: 'check'
                        id: chk_f
                        color:0,0,0,1
                    Label:
                        text:'F'
                        color:0,0,0,1
                    CheckBox:
                        group: 'check'
                        color:0,0,0,1
                        id: chk_m
                    Label:
                        color:0,0,0,1
                        text:'M'
                    
                #3
                
                Label:
                    font_size: 18
                    color:0,0,0,1
                    text:'Idade: '
                
                Label:
                    color:0,0,0,1
                    font_size: 18
                    text:'Peso: '
                 #4 
                TextInput:
                    id:idade
                    font_size: 26
                  # unicode: True
                  #  height: '5sp'
                  #  width: '5sp'

               
                    
                TextInput:
                    id:peso_txt
                    font_size: 26
                    multiline: False







                #5
                Botao_confirma:
                    id: ok
                    font_size: 18
                    color:0,0,0,1
                    text:'OK'
                    on_release:root.calcular()
                Botao_cancelar:
                    id: limpar
                    color:0,0,0,1
                    font_size: 18
                    text:'Limpar'
                    on_release:root.limpar()
                Label:
                    color:0,0,0,1
                    text:'Resultado - '
                Label:
                    color:0,0,0,1
                    id:valor
                    font_size:'20sp'        




    
<TAXACALORICA>:
    BoxLayout:
        
        orientation:'vertical'
        canvas:
            Color:
                rgba:1,0.515,0,1
            Rectangle:
                size:self.size
                pos:self.pos
        ActionBar:
            
            ActionView:
                
                ActionPrevious:
                    title:'Taxa Calorica'
                    on_release:app.root.current = 'calculo'
                ActionButton:
                    text:'Consular Historico'
                    on_release:app.root.current = 'historico_atv'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        BoxLayout:
            size_hint_y:None
            orientation:'vertical'
            GridLayout:
                id: box
                #pos:self.pos
                rows: 1
                cols: 8
                padding: 20
                    #width:'20sp'
                
                    #spacing: 20

          
                CheckBox:
                    group: 'check'
                    id: chk_corrida
                    color:0,0,0,1
                Label:
                    text:'Corrida'
                    color:0,0,0,1
                CheckBox:
                    group: 'check'
                    color:0,0,0,1
                    id: chk_caminhada
                Label:
                    color:0,0,0,1
                    text:'Caminhada'
                CheckBox:
                    group: 'check'
                    color:0,0,0,1
                    id: chk_natacao
                Label:
                    color:0,0,0,1
                    text:'Natacao'
                CheckBox:
                    color:0,0,0,1
                    group: 'check'
                    id: chk_ciclismo
                Label:
                    color:0,0,0,1
                    text:'Ciclismo'

        BoxLayout:
            #spacing: 10
            padding: 50
            GridLayout:
                id: box
                rows: 3
                cols: 2
                #padding: 10
                spacing: 10

               #1
                Label:
                    font_size: 18
                    color:0,0,0,1
                    text:'Duracao da atividade: '
                
              
                 #2  
                TextInput:
                    id:temp_atv
                    color:0,0,0,1
                    font_size: 26
                  # unicode: True
                  #  height: '5sp'
                  #  width: '5sp'


                #5
                Botao_confirma:
                    id: ok
                    font_size: 18
                    color:0,0,0,1
                    text:'OK'
                    on_release:root.calcular()
                Botao_cancelar:
                    id: limpar
                    color:0,0,0,1
                    font_size: 18
                    text:'Limpar'
                    on_release:root.limpar()
                Label:
                    color:0,0,0,1
                    text:'Resultado - '
                Label:
                    color:0,0,0,1
                    id:valor
                    font_size:'20sp'        


<historico_atv>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    #icon: 'image/bat.png'
                    title:'Historico da taxa de gasto calorico por atividade'
                    on_release:app.root.current = 'taxacalorica'
                ActionButton:
                    icon: 'image/bat.png'
                    text:'Menu'
                    on_release:app.root.current ='menu'
                ActionButton:
                    #icon: 'sair.jpeg'
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height


<CALCULADORA>:
    
    BoxLayout:
        
        orientation:'vertical'
        canvas:
            Color:
                rgba:1,0.515,0,1
            Rectangle:
                size:self.size
                pos:self.pos
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Calculadora'
                    on_release:app.root.current = 'calculo'
                ActionButton:
                    text:'Inicio'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        BoxLayout:
            height:'550dp'
            
            
            padding:'80sp'
            spacing:'50sp'
            
           
            CalcGridLayout:
                id: calculator
                display: entry
                rows: 5
                padding: 10
                spacing: 10
 
    # Where input is displayed
                BoxLayout:
                    TextInput:
                        id: entry
                        font_size: 32
                        multiline: False
 
    # When buttons are pressed update the entry
                BoxLayout:
                    spacing: 10
                    CustButton:
                        text: "7"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "8"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "9"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "+"
                        on_press: entry.text += self.text
 
                BoxLayout:
                    spacing: 10
                    CustButton:
                        text: "4"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "5"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "6"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "-"
                        on_press: entry.text += self.text
 
                BoxLayout:
                    spacing: 10
                    CustButton:
                        text: "1"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "2"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "3"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "*"
                        on_press: entry.text += self.text
 
    # When equals is pressed pass text in the entry
    # to the calculate function
                BoxLayout:
                    spacing: 10
                    CustButton:
                        text: "AC"
                        on_press: entry.text = ""
                    CustButton:
                        text: "0"
                        on_press: entry.text += self.text
                    CustButton:
                        text: "="
                        on_press:calculator.calculate(entry.text)
                    CustButton:
                        text: "/"
                        on_press: entry.text += self.text
    